### ISSUE TITLE
Erro na partida 'simulada '

### ISSUE THREAD

**Issue by guidoferrario** [aronsales/informatica29PapaiNoel#14]
Encontrei um erro no preenchimento do tabuleiro no modo de jogo em que a partida é 'simulada' (Computador x Computador).
![erro git](https://cloud.githubusercontent.com/assets/13753083/12004934/31ced586-ab61-11e5-9949-8fd10098a160.jpg)

**Comment by aronsales** [comment]
O problema era que o `if` onde trocava o turno, estava dentro do `while`.
Problema resolvido.
