### ISSUE TITLE
Criar Wiki

### ISSUE THREAD

**Issue by guidoferrario** [aronsales/informatica29PapaiNoel#16]
Acho que poderíamos ir adiantando a criação do Wiki. Concorda?
Alguma sugestão de tópico?

**Comment by aronsales** [comment]
Acho que poderíamos falar um pouco sobre o jogo da velha, as regras que são usadas, o processo de criação do código, além de informações sobre autores.

**Comment by guidoferrario** [comment]
Wiki criada!
