### ISSUE TITLE
Warning na compilação

### ISSUE THREAD

**Issue by aronsales** [aronsales/informatica29PapaiNoel#20]
Quando se compila, aparecem inúmeros warning, que não sei como resolver, peço ajuda para solucionar esse problema.
`warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]`

**Comment by guidoferrario** [comment]
Modificações realizadas. O Warning acontecia pela falta falta de parenteses entre os blocos lógicos.
